### ISSUE TITLE
The newest version of APM(983252) provokes an error. 

### ISSUE THREAD

**Issue by tonymin-gamedev** [Ray-Adams/APM#1]
{"message":"Uncaught Error: Unknown message index","filename":"https://arras.io/bundle.js?1577642780551","lineno":162,"colno":32,"error":"Error: Unknown message index"}

Code: https://greasyfork.org/ru/scripts/438236-arras-io-aimbot-script
Just replace version in "@require" to the newest and the error will appear.

**Comment by Ray-Adams** [comment]
I'm unable to reproduce this error with the latest version of APM (v1.1.3).

**Comment by Ray-Adams** [comment]
Thanks! The problem should be fixed now in v1.2.0
